<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/order.proto

namespace Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>demo.OrderdetailsResponse</code>
 */
class OrderdetailsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .demo.Orders order_list = 1;</code>
     */
    private $order_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Demo\Orders[] $order_list
     * }
     */
    public function __construct($data = NULL) {
        \Demo\Orders\Metadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .demo.Orders order_list = 1;</code>
     * @return RepeatedField<\Demo\Orders>
     */
    public function getOrderList()
    {
        return $this->order_list;
    }

    /**
     * Generated from protobuf field <code>repeated .demo.Orders order_list = 1;</code>
     * @param \Demo\Orders[] $var
     * @return $this
     */
    public function setOrderList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Demo\Orders::class);
        $this->order_list = $arr;

        return $this;
    }

}

