<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/order.proto

namespace Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>demo.Orders</code>
 */
class Orders extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 webordernumber = 1;</code>
     */
    protected $webordernumber = 0;
    /**
     * Generated from protobuf field <code>int32 originalwebordernumber = 2;</code>
     */
    protected $originalwebordernumber = 0;
    /**
     * Generated from protobuf field <code>bool isactive = 3;</code>
     */
    protected $isactive = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp orderdatetime = 4;</code>
     */
    protected $orderdatetime = null;
    /**
     * Generated from protobuf field <code>string paymentname = 5;</code>
     */
    protected $paymentname = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $webordernumber
     *     @type int $originalwebordernumber
     *     @type bool $isactive
     *     @type \Google\Protobuf\Timestamp $orderdatetime
     *     @type string $paymentname
     * }
     */
    public function __construct($data = NULL) {
        \Demo\Orders\Metadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 webordernumber = 1;</code>
     * @return int
     */
    public function getWebordernumber()
    {
        return $this->webordernumber;
    }

    /**
     * Generated from protobuf field <code>int32 webordernumber = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setWebordernumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->webordernumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 originalwebordernumber = 2;</code>
     * @return int
     */
    public function getOriginalwebordernumber()
    {
        return $this->originalwebordernumber;
    }

    /**
     * Generated from protobuf field <code>int32 originalwebordernumber = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginalwebordernumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->originalwebordernumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isactive = 3;</code>
     * @return bool
     */
    public function getIsactive()
    {
        return $this->isactive;
    }

    /**
     * Generated from protobuf field <code>bool isactive = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsactive($var)
    {
        GPBUtil::checkBool($var);
        $this->isactive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp orderdatetime = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getOrderdatetime()
    {
        return $this->orderdatetime;
    }

    public function hasOrderdatetime()
    {
        return isset($this->orderdatetime);
    }

    public function clearOrderdatetime()
    {
        unset($this->orderdatetime);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp orderdatetime = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setOrderdatetime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->orderdatetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string paymentname = 5;</code>
     * @return string
     */
    public function getPaymentname()
    {
        return $this->paymentname;
    }

    /**
     * Generated from protobuf field <code>string paymentname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentname($var)
    {
        GPBUtil::checkString($var, True);
        $this->paymentname = $var;

        return $this;
    }

}

