<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/order.proto

namespace Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>demo.WebordersRequest</code>
 */
class WebordersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * This is a list of strings (JSON array equivalent: ["val1", "val2"])
     *
     * Generated from protobuf field <code>repeated string weborders = 1;</code>
     */
    private $weborders;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $weborders
     *           This is a list of strings (JSON array equivalent: ["val1", "val2"])
     * }
     */
    public function __construct($data = NULL) {
        \Demo\Orders\Metadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * This is a list of strings (JSON array equivalent: ["val1", "val2"])
     *
     * Generated from protobuf field <code>repeated string weborders = 1;</code>
     * @return RepeatedField<string>
     */
    public function getWeborders()
    {
        return $this->weborders;
    }

    /**
     * This is a list of strings (JSON array equivalent: ["val1", "val2"])
     *
     * Generated from protobuf field <code>repeated string weborders = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setWeborders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->weborders = $arr;

        return $this;
    }

}

