<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/order.proto

namespace Demo\Orders\Metadata;

class Order
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x90\x03\x0A\x11proto/order.proto\x12\x04demo\"%\x0A\x10WebordersRequest\x12\x11\x0A\x09weborders\x18\x01 \x03(\x09\"8\x0A\x14OrderdetailsResponse\x12 \x0A\x0Aorder_list\x18\x01 \x03(\x0B2\x0C.demo.Orders\"\x9A\x01\x0A\x06Orders\x12\x16\x0A\x0Ewebordernumber\x18\x01 \x01(\x05\x12\x1E\x0A\x16originalwebordernumber\x18\x02 \x01(\x05\x12\x10\x0A\x08isactive\x18\x03 \x01(\x08\x121\x0A\x0Dorderdatetime\x18\x04 \x01(\x0B2\x1A.google.protobuf.Timestamp\x12\x13\x0A\x0Bpaymentname\x18\x05 \x01(\x092O\x0A\x0COrderService\x12?\x0A\x09GetOrders\x12\x16.demo.WebordersRequest\x1A\x1A.demo.OrderdetailsResponseB\x1E\xCA\x02\x04Demo\xE2\x02\x14Demo\\Orders\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

