<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/user.proto

namespace Demo\Users\Metadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD9\x01\x0A\x10proto/user.proto\x12\x04demo\"\x1E\x0A\x0BUserRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x05\"7\x0A\x0CUserResponse\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\x12\x0C\x0A\x04name\x18\x02 \x01(\x09\x12\x0D\x0A\x05email\x18\x03 \x01(\x092?\x0A\x0BUserService\x120\x0A\x07GetUser\x12\x11.demo.UserRequest\x1A\x12.demo.UserResponseB\x1D\xCA\x02\x04Demo\xE2\x02\x13Demo\\Users\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

